# Generated by Django 3.0.6 on 2020-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='car_model',
            options={'verbose_name': 'Automobilio Modelis', 'verbose_name_plural': 'Automobiliu Modeliai'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Uzsakymas', 'verbose_name_plural': 'Uzsakymai'},
        ),
        migrations.AlterModelOptions(
            name='order_line',
            options={'verbose_name': 'Uzsakymo Linija', 'verbose_name_plural': 'Uzsakymu Linijos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='service_price',
            options={'verbose_name': 'Paslaugos Kaina', 'verbose_name_plural': 'Paslaugu Kainos'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Patvirtinta'), ('v', 'Vykdoma'), ('a', 'Atlikta'), ('t', 'Atšaukta')], default='a', help_text='Statusas', max_length=1),
        ),
    ]
