# Generated by Django 3.0.6 on 2020-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200520_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order_line',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Patvirtinta'), ('v', 'Vykdoma'), ('a', 'Atlikta'), ('t', 'Atšaukta')], default='a', help_text='Statusas', max_length=1),
        ),
    ]
