# Generated by Django 3.0.6 on 2020-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_orderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line',
            name='order_total_price',
            field=models.FloatField(null=True, verbose_name='Uzsakymo kaina'),
        ),
    ]
